import json, re
from datetime import datetime
from pathlib import Path

OUTPUT_DIR = Path(__file__).parent.parent / "output"

def save_digest(digest):
    OUTPUT_DIR.mkdir(exist_ok=True)
    date = digest.get("date", datetime.now().strftime("%Y-%m-%d"))
    slug = re.sub(r"[^a-z0-9]+","-",digest.get("topic","research").lower())[:40]
    base = f"{date}_{slug}"
    json_path = OUTPUT_DIR / f"{base}.json"
    html_path = OUTPUT_DIR / f"{base}.html"
    json_path.write_text(json.dumps(digest, indent=2, ensure_ascii=False), encoding="utf-8")
    html_path.write_text(_render(digest), encoding="utf-8")
    print(f"\nSaved:\n  {json_path}\n  {html_path}")
    return {"json_path":str(json_path),"html_path":str(html_path),"success":True}

def _render(d):
    topic = d.get("topic","Digest")
    date = d.get("date","")
    summary = d.get("summary","")
    findings = "".join(f"<li>{f}</li>" for f in d.get("key_findings",[]))
    themes = "".join(f'<div class="theme"><h3>{t["name"]}</h3><ul>{"".join(f"<li>{x}</li>" for x in t["findings"])}</ul></div>' for t in d.get("themes",[]))
    citations = "".join(f'<div class="citation"><span class="num">[{i+1}]</span><div><a href="{c.get("url","#")}" target="_blank">{c.get("title","Source")}</a><span class="src"> — {c.get("source","")}</span><p class="snippet">{c.get("snippet","")}</p></div></div>' for i,c in enumerate(d.get("citations",[])))
    read_next = "".join(f'<div class="rn"><a href="{r.get("url","#")}" target="_blank">→ {r.get("title","")}</a><p>{r.get("reason","")}</p></div>' for r in d.get("read_next",[]))
    return f"""<!DOCTYPE html><html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>{topic} — {date}</title>
<style>:root{{--bg:#fafaf8;--card:#fff;--border:#e8e6de;--text:#1a1a18;--muted:#6b6a64;--accent:#534AB7;--accent-bg:#EEEDFE;--teal:#0F6E56;--teal-bg:#E1F5EE}}
@media(prefers-color-scheme:dark){{:root{{--bg:#16161a;--card:#1e1e24;--border:#2e2e38;--text:#e8e6de;--muted:#9c9a92}}}}
*{{box-sizing:border-box;margin:0;padding:0}}body{{font-family:system-ui,sans-serif;background:var(--bg);color:var(--text);line-height:1.7}}
.header{{background:var(--accent);color:#fff;padding:40px 24px 32px}}.header h1{{font-size:22px;font-weight:500}}
.badge{{display:inline-block;font-size:11px;padding:2px 10px;border-radius:20px;background:rgba(255,255,255,.2);margin-right:8px}}
.container{{max-width:780px;margin:0 auto;padding:32px 24px}}.section{{background:var(--card);border:1px solid var(--border);border-radius:12px;padding:24px;margin-bottom:20px}}
h2{{font-size:13px;font-weight:500;color:var(--muted);text-transform:uppercase;letter-spacing:.05em;margin-bottom:14px}}
.summary{{font-size:16px;line-height:1.8}}.theme{{margin-bottom:16px;padding-bottom:16px;border-bottom:1px solid var(--border)}}.theme:last-child{{border-bottom:none;margin-bottom:0;padding-bottom:0}}
.theme h3{{font-size:14px;font-weight:500;color:var(--accent);margin-bottom:8px}}ul{{padding-left:18px}}li{{font-size:14px;margin-bottom:6px}}
.citation{{display:flex;gap:12px;margin-bottom:14px;align-items:flex-start}}.num{{font-size:12px;font-weight:600;color:var(--accent);background:var(--accent-bg);border-radius:4px;padding:1px 6px;flex-shrink:0}}
.citation a{{font-size:14px;font-weight:500;color:var(--accent);text-decoration:none}}.src{{font-size:12px;color:var(--muted)}}.snippet{{font-size:13px;color:var(--muted);margin-top:3px}}
.rn{{margin-bottom:12px;padding:12px 16px;background:var(--teal-bg);border-radius:8px}}.rn a{{font-size:14px;font-weight:500;color:var(--teal);text-decoration:none}}.rn p{{font-size:13px;color:var(--muted);margin-top:4px}}
.footer{{text-align:center;font-size:12px;color:var(--muted);padding:24px}}</style></head>
<body><div class="header"><div><span class="badge">📅 {date}</span><span class="badge">🔬 Daily Digest</span></div><h1 style="margin-top:12px">{topic}</h1></div>
<div class="container">
{f'<div class="section"><h2>Summary</h2><p class="summary">{summary}</p></div>' if summary else ""}
{f'<div class="section"><h2>Key Findings</h2><ul>{findings}</ul></div>' if findings else ""}
{f'<div class="section"><h2>Themes</h2>{themes}</div>' if themes else ""}
{f'<div class="section"><h2>Sources</h2>{citations}</div>' if citations else ""}
{f'<div class="section"><h2>What to Read Next</h2>{read_next}</div>' if read_next else ""}
<div class="footer">⚡ Generated by <strong>Nexus</strong> · Built by Redwan · Powered by Hermes Agent</div>
</div></body></html>"""
